# Use the official PostgreSQL image as the database
FROM postgres:13

# Expose the PostgreSQL port (default is 5432)
EXPOSE 5432

# Set environment variables for the PostgreSQL database (customize as needed)
ENV POSTGRES_DB yourdb
ENV POSTGRES_USER yourdbusername
ENV POSTGRES_PASSWORD yourdbpassword
