### login as normal user
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "pokemon@gmail.com",
  "password": "Pokemon!23"
}

### login as admin user
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "AdminUser!1"
}

### admin base64 token: YWRtaW5AZ21haWwuY29tOkFkbWluVXNlciEx

### register
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "firstName": "snackbar2",
  "lastName" : "kekbar2",
  "email" : "pokemon1@gmail.com",
  "password": "Pokemon!23",
  "terms": true
}

### all users
GET http://localhost:8080/user/all
Authorization:Basic cG9rZW1vbkBnbWFpbC5jb206UG9rZW1vbiEyMw==

### get single profile by firstname and lastname
GET http://localhost:8080/user/snackbar2/kekbar2
Authorization:Basic cG9rZW1vbkBnbWFpbC5jb206UG9rZW1vbiEyMw==

### delete single profile by firstname and lastname
DELETE http://localhost:8080/user/snackbar2/kekbar2/delete
Authorization:Basic cG9rZW1vbkBnbWFpbC5jb206UG9rZW1vbiEyMw==

### update profile

PUT http://localhost:8080/user/snackbar2/kekbar2/update
Content-Type: application/json
Authorization:Basic cG9rZW1vbjFAZ21haWwuY29tOlBva2Vtb24hMjM=

{
  "firstName": "pickachu123",
  "lastName": "blit123z",
  "password": "Oekemon123!",
  "email": "pokemon2@gmail.com"
}

