### deletes bootstrapped profile(pokemon@gmail.com)
DELETE http://localhost:8080/user/profile/delete
Content-Type: application/json
Authorization:Basic cG9rZW1vbkBnbWFpbC5jb206UG9rZW1vbiEyMw==


### register

POST http://localhost:8080/user/register
Content-Type: application/json

{
  "firstName": "snackbar2",
  "lastName" : "kekbar2",
  "email" : "pokemon@gmail.com",
  "password": "Pokemon!23",
  "terms": true
}


### update profile(email cannot be updated)

PUT http://localhost:8080/user/profile/update
Content-Type: application/json
Authorization:Basic cG9rZW1vbkBnbWFpbC5jb206UG9rZW1vbiEyMw==

{
  "firstName": "pickachu123",
  "lastName": "blit123z",
  "password": "Oekemon123!",
  "email": "pokemon@gmail.com"
}

### delete user
DELETE http://localhost:8080/user/profile/delete
Content-Type: application/json
Authorization:Basic cG9rZW1vbkBnbWFpbC5jb206UG9rZW1vbiEyMw==